accounts/urls.py
from django.urls import path,include
from .views import *

app_name="accounts"
# Create your views here.
urlpatterns = [
    path('profile/',profile_view, name='account_profile'),
    path('', include('allauth.urls')),  # Include allauth's URLs
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sitepages.urls',namespace='sitepages')),
    path('accounts/',include('allauth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepages/urls.py
from django.urls import path
from .views import *


app_name = 'sitepages'


urlpatterns = [
    path('',Home,name='homepage'),
    path('about/',About,name='aboutpage'),
    path('service/',Service,name='servicepage'),
    path('cars/',Car,name='carpage'),
    path('cars-detail/<str:car_slug>/',Car_details,name='car_details'),
    path('contact/',Contact,name='contactpage'),
    path('search_cars/',car_search, name='search-cars'),
    path('cars/<str:brand_name>/', cars_by_brand, name='cars_by_brand'),
    # path('cars/<int:car_id>/check_availability/', check_availability, name='check_availability'),
    path('booking/', booking, name='booking'),
    path('booking/confirm/',confirm_booking, name='confirm_booking'),

    # URL for payment methods (e.g., PayPal, bank transfer)
    path('payment/stripe/', stripe_payment, name='stripe_payment'),
    path('payment/success/', payment_success, name='payment_success'),  # Add your success view
    path('payment/success/stripe', payment_success_stripe, name='payment_success_stripe'),  # Add your success view
    path('payment/cancel/', payment_cancel, name='payment_cancel'),  
    path('payment/paypal/', show_paypal_payment, name='show_paypal_payment'),
    path('payment/paypal/submit/', paypal_payment, name='paypal_payment'), 
    path('booking-history/', booking_history, name='booking_history'),
]

templates/payment/cancel.html
{% extends 'sitepages/base1.html' %}
{% load static %}
{% block homepage_content %}

<!-- Page Header Start -->
<div class="container-fluid page-header">
    <h1 class="display-3 text-uppercase text-white mb-3">Payment Cancelled</h1>
    <div class="d-inline-flex text-white">
        <h6 class="text-uppercase m-0"><a class="text-white" href="">Home</a></h6>
        <h6 class="text-body m-0 px-3">/</h6>
        <h6 class="text-uppercase text-body m-0">Payment Cancelled</h6>
    </div>
</div>
<!-- Page Header Start -->


<!-- Display success and error messages -->
{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<div class="untree_co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center pt-5">
                <span class="display-3 thankyou-icon text-danger">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M16 8a8 8 0 1 1-16 0 8 8 0 0 1 16 0zm-1.5 0A6.5 6.5 0 1 0 1.5 8 6.5 6.5 0 0 0 14.5 8zM8.354 7.646a.5.5 0 0 1 0-.708L10.707 5.293a.5.5 0 0 1 .708.708L9.707 8l1.708 1.707a.5.5 0 0 1-.708.708L8.354 8.707a.5.5 0 0 1 0-.708z"/>
                        <path fill-rule="evenodd" d="M5.293 5.293a.5.5 0 0 1 .707 0L8 7.293l1.5-1.5a.5.5 0 0 1 .708.708L8.707 8l1.5 1.5a.5.5 0 0 1-.708.708L8 8.707l-1.5 1.5a.5.5 0 0 1-.708-.708L7.293 8 5.793 6.5a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </span>
                <h2 class="display-3 text-black">Payment Failed</h2>
                <p class="lead mb-5">Your payment was cancelled. Please try again.</p>
                <p><a href="/" class="btn btn-sm btn-outline-black">Back to Home</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/payment/paypal_payment.html
{% extends 'sitepages/base1.html' %}
{% load static %}
{% block homepage_content %}

<!-- Page Header Start -->
<div class="container-fluid page-header">
    <h1 class="display-3 text-uppercase text-white mb-3">Paypal Payment</h1>
    <div class="d-inline-flex text-white">
        <h6 class="text-uppercase m-0"><a class="text-white" href="">Home</a></h6>
        <h6 class="text-body m-0 px-3">/</h6>
        <h6 class="text-uppercase text-body m-0">Paypal Payment</h6>
    </div>
</div>
<!-- Page Header Start -->


<div class="container">
    <h1>Pay for your Car Rental</h1>
    <p>Car: {{ car_name }}</p>
    <!-- <p>Pickup Date: {{ pickup_datetime }}</p>
    <p>Dropoff Date: {{ dropoff_datetime }}</p> -->
    <p>Total Cost: {{ total_cost }} {{ currency }}</p>

    <form action="{% url 'sitepages:paypal_payment' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="total_cost" value="{{ total_cost }}">
        <input type="hidden" name="pickup_datetime" value="{{ pickup_datetime }}">
        <input type="hidden" name="dropoff_datetime" value="{{ dropoff_datetime }}">
        <input type="hidden" name="currency" value="{{ currency }}">
        <!-- Include any other hidden fields you need here -->

        <button type="submit" class="btn btn-primary">Proceed to PayPal</button>
    </form>
</div>

{%endblock%}

templates/payment/success.html
{% extends 'sitepages/base1.html' %}
{% load static %}
{% block homepage_content %}

	 <!-- Page Header Start -->
     <div class="container-fluid page-header">
        <h1 class="display-3 text-uppercase text-white mb-3">Payment Success</h1>
        <div class="d-inline-flex text-white">
            <h6 class="text-uppercase m-0"><a class="text-white" href="">Home</a></h6>
            <h6 class="text-body m-0 px-3">/</h6>
            <h6 class="text-uppercase text-body m-0">Payment Success</h6>
        </div>
    </div>
    <!-- Page Header Start -->

		

		<div class="untree_co-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center pt-5">
          <span class="display-3 thankyou-icon text-primary">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
              <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
            </svg>
          </span>
          <h2 class="display-3 text-black">Thank you!</h2>
          <p class="lead mb-5">You Booking was successfuly completed.Check the email you provided when filling the booking details for more info.</p>
          <p><a href="/" class="btn btn-sm btn-outline-black">Back to Home</a></p>
        </div>
      </div>
    </div>
  </div>


  {%endblock%}
		